# Generated by Django 4.2 on 2023-09-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='runtime_minutes',
            field=models.CharField(max_length=15),
        ),
    ]
