# Generated by Django 4.2 on 2023-09-27 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0003_remove_film_genre_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='cataloge.country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='cataloge.genre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='cataloge.language'),
        ),
    ]
