# Generated by Django 4.2 on 2023-09-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0004_alter_film_country_alter_film_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to='posters/'),
        ),
    ]
